### PR TITLE
make text input more user-friendly 

### PR DESCRIPTION
**Pull request by Blizarre**
The use of the default `read` command will not allow the user to use arrow keys and shorcuts to enter the data when doing a replace or entering any input, which can be frustrating. Besides, backslashed are interpreted and can be mangled.

- Using the "-e" option will trigger the use of the readline library: you can then, as expected in bash, use the arrow keys and all shortcuts to move around the line before pressing enter.
- Using the "-r" option will prevent the interpretation of the "\" and insert them as typed, useful when pasting code:

http://wiki.bash-hackers.org/commands/builtin/read#read_without_-r

```
$ read -r TESTR
Hello \'World\'
$ read TEST
Hello \'World\'
$ echo $TEST
Hello 'World'
$ echo $TESTR
Hello \'World\'
```

The user group seems to have been removed, so I created this PR directly.

### CODE REVIEW

**Comment by inkarkat** [comment]
A small detail, yet a valuable contribution. Thank you!

Please note that Gina is the only person who can accept this, and she's been notably absent in the past months / years. So don't be disappointed. People will still see this and may pull it into their respective forks.

**Comment by karbassi** [comment]
@Blizarre and @inkarkat, you can submit the PR at [todotxt/todo.txt-cli](https://github.com/todotxt/todo.txt-cli) if you'd like.

**Comment by Blizarre** [comment]
Many thanks for the replies, I noticed the project was not very active at the moment, but I had no idea this fork was almost abandoned. I will post the PR to todotxt, thanks @karbassi!

**Comment by awitherow** [comment]
@karbassi thanks for stepping up! I love this tool and I look forward to its evolution!

**Review by inkarkat — APPROVED** [review]
As I already mentioned, nice addition.

**Pull request merged**
