### PR TITLE
allow parameters / options in default action

### PR DESCRIPTION
**Pull request by butonic**
this allows me to use https://github.com/markwu/todo-cli-plugins/blob/master/view and set is as the default action with `export TODOTXT_DEFAULT_ACTION="view context"`

### CODE REVIEW

**Review by inkarkat — CHANGES_REQUESTED** [review]
Needs tests and documentation.

**Comment by karbassi** [comment]
@butonic could you write tests for this?

**Comment by butonic** [comment]
I moved to another tool. But you can edit this branch or close the PR.

**Comment by chrysle** [comment]
I would write some tests and docs, but can't edit this.

**Comment by inkarkat** [comment]
> I would write some tests and docs, but can't edit this.

Just create your own branch (off butonic's `master` branch), and submit a separate PR.

**Pull request merged**
