### PR TITLE
Fix no end-of-line bug

### LINKED ISSUE #294: add command does not check/add preceding newline character
I think this should be considered a **bug** because it can cause data loss/corruption.

**Current behavior:**

The **add** command fails to add a new task entry if the `todo.txt` file does not end in a newline (`\n`). This can happen easily with certain editors (such as Mousepad) that do not automatically add a newline character at the end of a file.

**Steps to reproduce:**

This behavior can be simulated with Nano's `--nonewlines` option, or with `echo -n` like this:

```
$ echo -n "This is a low/no priority task" >| todo.txt
```

At this point, the `todo.txt` file has one task but does *not* have a line break at the end.

Now we can use the **add** command to create a new task:

```
$ todo-txt add "(A) This is a high-priority task"
```

And then list the tasks:

```
$ todo-txt ls
This is a low/no priority task(A) This is a high-priority task
```

The new high-priority task has been "lost" because it was not placed on a line of its own.

**Expected behavior:**

*todo-txt* should check for a newline character (`\n`) at the end of the file and, if it is missing, add it before the new task entry.

**Versions:**

- todo-txt 2.11.0 on Debian GNU/Linux
- bash 5.0.3(1)-release

### PR DESCRIPTION
**Pull request by inkarkat**
This fixes #294 by passing the target file through `sed` (when adding or moving, both of which use simple `>>` shell redirection which is susceptible to this) to add a trailing newline (EOL) character if one is missing.

**Before submitting a pull request,** please make sure the following is done:

- [X] Fork [the repository](https://github.com/todotxt/todo.txt-cli) and create your branch from `master`.
- [X] If you've added code that should be tested, add tests!
- [X] Ensure the test suite passes.
- [X] Format your code with [ShellCheck](https://www.shellcheck.net/).
- [X] Include a human-readable description of what the pull request is trying to accomplish.
- [X] Steps for the reviewer(s) on how they can manually QA the changes.
- [X] Have a `fixes #XX` reference to the issue that this pull request fixes.

### CODE REVIEW

**Comment by inkarkat** [comment]
@karbassi Somehow, the CI build isn't triggered on this: _This branch has not been deployed_; I was able to restart an old PR build in Travis, so that still works; maybe the GitHub trigger didn't work. I don't have admin rights to check this.

It's gotten a bit silent here; I've answered a few issues and PRs in the past, but other than that, not much has happened. If you could briefly review my two other open PRs (#271 and #273), I would merge them all in soon. I hope you're fine!

**Comment by karbassi** [comment]
@inkarkat we might want to move over to Github Actions at some point.

I ran the tests and it failed.

```
cd tests && ./t1850-move.sh 
* FAIL 1: basic move with implicit source 1
todo.sh -f move 1 done.txt | sed "s#'[^']\+/\([^/']\+\)'#'\1'#g" 
--- expect	2020-03-27 18:37:30.000000000 +0000
+++ output	2020-03-27 18:37:30.000000000 +0000
@@ -1,2 +1,2 @@
 1 (B) smell the uppercase Roses +flowers @outside
-TODO: 1 moved from 'todo.txt' to 'done.txt'.
+TODO: 1 moved from 'tests/trash directory.t1850-move/todo.txt' to 'tests/trash directory.t1850-move/done.txt'.
*   ok 2: basic move with implicit source 2
*   ok 3: basic move with implicit source 3
* FAIL 4: basic move with passed source 1
todo.sh -f move 2 todo.txt done.txt | sed "s#'[^']\+/\([^/']\+\)'#'\1'#g" 
--- expect	2020-03-27 18:37:30.000000000 +0000
+++ output	2020-03-27 18:37:30.000000000 +0000
@@ -1,2 +1,2 @@
 2 x 2009-02-13 smell the coffee +wakeup
-TODO: 2 moved from 'done.txt' to 'todo.txt'.
+TODO: 2 moved from 'tests/trash directory.t1850-move/done.txt' to 'tests/trash directory.t1850-move/todo.txt'.
*   ok 5: basic move with passed source 2
*   ok 6: basic move with passed source 3
* FAIL 7: move to destination without EOL 1
todo.sh -f move 2 todo.txt done.txt | sed "s#'[^']\+/\([^/']\+\)'#'\1'#g" 
--- expect	2020-03-27 18:37:30.000000000 +0000
+++ output	2020-03-27 18:37:30.000000000 +0000
@@ -1,2 +1,2 @@
 2 x 2009-02-13 smell the coffee +wakeup
-TODO: 2 moved from 'done.txt' to 'todo.txt'.
+TODO: 2 moved from 'tests/trash directory.t1850-move/done.txt' to 'tests/trash directory.t1850-move/todo.txt'.
*   ok 8: move to destination without EOL 2
*   ok 9: move to destination without EOL 3
* failed 3 among 9 test(s)
make: *** [tests/t1850-move.sh] Error 1
```

**Comment by karbassi** [comment]
We have GitHub Actions now! 👍 
The tests are failing. 👎

**Review by karbassi — CHANGES_REQUESTED** [review]
t1850-move fails on macOS

**Comment by inkarkat** [comment]
@karbassi Thank you for setting up the new CI builds; that's really great! (And I involuntarily demonstrated why it's so important to have them.)

I've fixed the compatibility problem; fortunately, that was an easy one and I didn't have to update my FreeBSD VM to see how barren it is in non-GNU land :-)

**Review by karbassi — APPROVED** [review]

**Comment by karbassi** [comment]
@inkarkat looks good. Merge.

**Pull request merged**
