### PR TITLE
Add color for task

### PR DESCRIPTION
**Pull request by dynobo**
**Before submitting a pull request,** please make sure the following is done:

- [x] Fork [the repository](https://github.com/todotxt/todo.txt-cli) and create your branch from `master`.
- [x] If you've added code that should be tested, add tests!
- [x] Ensure the test suite passes.
- [x] Format your code with [ShellCheck](https://www.shellcheck.net/).
- [x] Include a human-readable description of what the pull request is trying to accomplish.
- [x] Steps for the reviewer(s) on how they can manually QA the changes.
- [x] Have a `fixes #XX` reference to the issue that this pull request fixes.

**Added feature:**
New option in config file "COLOR_ID" to add highlighting for the number at the beginning of every task line (the task id),

**Steps for QA:**
- Please test various combinations of highlightings with tasks containing numbers, and see if a formatting get's messed up

### CODE REVIEW

**Comment by dynobo** [comment]
Fixes #266

**Comment by karbassi** [comment]
@dynobo The priority highlighting works, but the numbers do no. See below with my tests.


Screen Shot 2020-03-29 at 12 47 57 PM


Also, the test needs to have the numbers in front of the todo.txt

**Review by karbassi — CHANGES_REQUESTED** [review]
@dynobo see my above comment.

**Review by inkarkat — COMMENTED** [review]
Agree with closing; we've already accepted a more encompassing change.

**Pull request closed without merging**
