### PR TITLE
Create Changelog

### LINKED ISSUE #209: Move over Changelog from wiki to github and changelog.md
Move over wiki changelog to github release and changelog.md file. 

Reference: https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Changelog

### PR DESCRIPTION
**Pull request by gutierri**
Fixes #209, #225

### CODE REVIEW

**Comment by karbassi** [comment]
@gutierri Great start!

Couple of things before we can merge this:
- [x] Update the structure to match the pattern from [Keep A Changelog](http://keepachangelog.com/en/1.0.0/). I've started this for you.
- [x] Make sure you're working in a branch, not master. I suggest `feature/changelog`

**Comment by gutierri** [comment]
@karbassi You can merge it into another branch of this project. (OK **feature/changelog**)

**Comment by karbassi** [comment]
@gutierri Go ahead and create a new PR with the new branch and the changes requested above and I'll review and merge it!

Thanks @gutierri 👍

**Comment by karbassi** [comment]
@gutierri Any updates on this?

**Review by karbassi — APPROVED** [review]

**Pull request merged**
