### PR TITLE
README

### PR DESCRIPTION
**Pull request by gutierri**
#211

### CODE REVIEW

**Comment by karbassi** [comment]
Hello @gutierri! Thanks so much for getting the `README.md` started. It looks great so far.

Since the maintainers have access to update your PR, I'll update a few things in here as well.

**Comment by gutierri** [comment]
tty3

@karbassi What do you think about this?

**Review by karbassi — APPROVED** [review]

**Comment by gutierri** [comment]
@karbassi maybe it would be interesting to create a (sub) wiki to put it to use. The README is quite large.

**Comment by karbassi** [comment]
@gutierri it's okay that the README is large. We want to keep this information in the codebase, not in a wiki. Moreover, the wiki is part of github, not the codebase.

**Pull request merged**
