### PR TITLE
Add initial fish subcommand completions

### PR DESCRIPTION
**Pull request by asfaltboy**
**Before submitting a pull request,** please make sure the following is done:

- [x] Fork [the repository](https://github.com/todotxt/todo.txt-cli) and create your branch from `master`.
- [ ] If you've added code that should be tested, add tests!
- [ ] Ensure the test suite passes.
- [ ] Format your code with [ShellCheck](https://www.shellcheck.net/).
- [x] Include a human-readable description of what the pull request is trying to accomplish.
- [ ] Steps for the reviewer(s) on how they can manually QA the changes.
- [x] Have a `fixes #XX` reference to the issue that this pull request fixes.

**Description**

This adds fish shell command completions as mentioned in #142 ;  this is by no means complete but
it's a good start for new users, like myself, who can't remember what's what yet.

Dear reviewer, please [try out "fish shell"][1] copying this file into `~/.config/fish/completions/` should enable the completions. The parsing of options' help might be overkill if the command don't change very often.
Please add any other ideas or suggestions for this initial MVP.

**Implemented**

- [x] initial subcommands
- [x] project completion for add*

**Todo**

- [ ] command options
- [ ] complete tags, priorities and maybe date (today?)
- [ ] aliases

**References**

* https://fishshell.com/docs/current/completions.html
* https://fishshell.com/docs/current/cmds/commandline.html
* https://fishshell.com/docs/current/cmds/function.html
* https://fishshell.com/docs/current/commands.html
* https://fishshell.com/docs/current/cmds/string.html
* https://rootnroll.com/d/fish-shell/

[1]: https://fishshell.com

### CODE REVIEW

**Comment by inkarkat** [comment]
Looks like a welcome addition for Fish users. (I'm not sure how many that would be, though.)

I wonder whether it wouldn't be better to implement the completion in terms of the existing Bash completion, if necessary through extracting some common generic functions. This way, the nice set of tests of Bash completion (10 files so far) could be leveraged, and maybe even all of the functionality could be offered for Fish as well.

The lack of test coverage worries me the most; the existing developers will probably not be well versed in Fish syntax, and unless you come back and complete the implementation soon, there will be requests and maybe even patches, and then who's gonna decide whether to accept it (without test coverage)?

I know that it's a lot more effort and challenge to come up with tests, especially for something like completion that is quite integrated into the shell itself. Maybe it would be better to keep this as a separate project so far; we could add a link here (_Fish shell users refer to asfaltboy/todo.txt-cli-fish-completion_). It could still be integrated here later, once test coverage has been added or the project has matured so much and received so many stars that it could be deemed "stable and practically tested".

I hope I haven't put you off as being too hesitant and negative; I just remember when I submitted my first changes to todo.txt, and Gina challenged me as well to add test coverage, and it helped both me as a developer and also the project's quality in the end.

**Comment by inkarkat** [comment]
Regarding the functionality, I wonder why you're restricting `+project` completion just to `add[m]` actions, as projects make sense with several other actions, too. The approach of the Bash completion is to rather offer too much than too little.

Adding completion for `@context` is analog to `+project`, so it would be a simple matter of copy-and-paste to add that, too.

**Review by inkarkat — CHANGES_REQUESTED** [review]
Implementation is incomplete (it even lists todos in the comments), and no test coverage at all (which we do have for Bash completion).

My recommendation is to have this as a separate project (which we could link to), until it's more complete, tested, and had user feedback.

**Comment by karbassi** [comment]
I'm going to keep this open for a month to give @asfaltboy time to bring the PR to a mergeable state.

@asfaltboy We'd love to merge this PR, but as @inkarkat noted, it's incomplete at this point. Could you finish the TODOs and write some tests in the next month?

**Comment by asfaltboy** [comment]
I could not find any concensus around how to test fish completions, so I don't mind scraping it and maybe linking to it in some doc/README/FAQ in case other people ask around

**Comment by markstos** [comment]
Fish completions have been published in this Gist:   https://gist.github.com/NijeboerFrank/7067007a43658ff94e2c954b83c08e43?permalink_comment_id=4587602

**Pull request closed without merging**
