### PR TITLE
Create CODE_OF_CONDUCT.md

### LINKED ISSUE #216: Create a Code of Conduct

### PR DESCRIPTION
**Pull request by karbassi**
Fixes #216
Related to #212 and #211 

Still need to add the email address though.

@ginatrapani, is there a shared gmail/protonmail email address we could use?

### CODE REVIEW

**Comment by ginatrapani** [comment]
> is there a shared gmail/protonmail email address we could use?

There isn't currently a private email address -- only the mailing list address. I've always pushed for everything that could possibly be done in public to be, but otherwise people would email me privately.

That's no longer a good solution and we should probably set up an address that forward to the core team. Lemme know if I can help with that -- do we want a todotxt.org address?

**Review by ginatrapani — APPROVED** [review]
Core team email address setup/decision withstanding, this looks great! 👍

**Comment by amcintosh** [comment]
👍

**Comment by karbassi** [comment]
>That's no longer a good solution and we should probably set up an address that forward to the core team. Lemme know if I can help with that -- **do we want a todotxt.org address?**

@ginatrapani I think setting up a `info@todotxt.org` or `help@todotxt.org` that could be logged into by any of the owners would be a good next step.

Tbh, I don't know how other groups do it. What does the Bootstrap team do, for instance?

**Comment by karbassi** [comment]
Merging, we'll figure out the email address at a later time. No reason to block the PR.

**Pull request merged**
