### PR TITLE
Different folder to copy ~/.todo.cfg for macOS on arm/x86 CPU

### PR DESCRIPTION
**Pull request by xqliu**
**Before submitting a pull request,** please make sure the following is done:

- [x] Fork [the repository](https://github.com/todotxt/todo.txt-cli) and create your branch from `master`.
- [x] If you've added code that should be tested, add tests!
- [x] Ensure the test suite passes.
- [x] Format your code with [ShellCheck](https://www.shellcheck.net/).
- [x] Include a human-readable description of what the pull request is trying to accomplish.
- [x] Steps for the reviewer(s) on how they can manually QA the changes.
- [x] Have a `fixes #XX` reference to the issue that this pull request fixes.

### CODE REVIEW

**Review by inkarkat — COMMENTED** [review]
I'm not an Apple user, so I'm missing a bit of context here. It looks like the (default) install location of Homebrew has changed for Apple's new M1 processor, right? A link to Apple documentation would have been helpful here. (But then again, maybe this is common knowledge to Apple users.)

I'm also a bit puzzled by the distinction in the comments. Shouldn't it be _macOS/x64_ (the current spelling of Apple's OS is [macOS](https://en.wikipedia.org/wiki/MacOS)) vs. _macOS/ARM64_? _Apple silicon_ (I think that's what you've intended to write) is not a very precise term.

**Comment by xqliu** [comment]
Dear, please see the follow for homebrew install directory on Mac with m1 chip

https://mac.install.guide/homebrew/index.html

Here is a screenshot:

image

For the wording, I think your suggestion is quite good. let me change them according.

Thanks for your review

**Review by inkarkat — APPROVED** [review]
Thanks for adding the background information about the Homebrew directory change!

**Review by inkarkat — APPROVED** [review]

**Comment by karbassi** [comment]
@xqliu could you work on the tests? They are failing for macOS.

https://github.com/todotxt/todo.txt-cli/runs/4216039911?check_suite_focus=true

**Comment by inkarkat** [comment]
> @xqliu could you work on the tests? They are failing for macOS.

This PR only updates the readme, no code; I think this is a general problem, and this PR simply is the first run where it surfaced.

The failing test is _add to file without EOL_; I suspect that the macOS version (or some dependencies) got updated, and now there's a different behavior of linefeed handling (somehow), and that's breaking the test.

Does GitHub automatically update the CI system images? It would be fantastic if such an update would also automatically trigger the CI, so that any compatibility issue could be detected right away and not just when the next PR is submitted. Alternatively, if there's a feed / event / notification one could subscribe to, one of us could then manually trigger a CI build.

**Comment by karbassi** [comment]
This is my fault. 🙃

I should have looked at the changes and not just the CI checks.

Approved 👍🏽 and merging 🎉.

**Pull request merged**
