### PR TITLE
Remove newline from echo confirmation on `todo rm`

### PR DESCRIPTION
**Pull request by TiredSounds**
Seemed to be unintentional as `-n` is used in other places in the script when getting input.

### CODE REVIEW

**Review by inkarkat — CHANGES_REQUESTED** [review]
The two `y/n` confirmations both do not use `-n`, only the queries for data do. I'm not against changing this, but it should be applied to both (and likely extracted into a `confirm()` function).

**Comment by karbassi** [comment]
@TiredSounds  could you update the code to also include `-n` on line 1280?

https://github.com/todotxt/todo.txt-cli/blob/8d83ff6b368f748ba498a3d604a02961f1ef4673/todo.sh#L1279-L1281

```bash
echo "Move '$todo' from $src to $dest? (y/n)"
```
to
```bash
echo -n "Move '$todo' from $src to $dest? (y/n)"
```

**Comment by chrysle** [comment]
Should this be closed or can maintainers make the requested changes?

**Comment by inkarkat** [comment]
There's a fix pending at https://github.com/inkarkat/todo.txt-cli/commit/466265175bdb119f1dbe1ecb5dd78af37d4528f3

**Comment by inkarkat** [comment]
Obsolete.

**Pull request closed without merging**
